apiVersion: v1
kind: Service
metadata:
  name: {{ template "jenkins.fullname" . }}
  labels:
    app: {{ template "jenkins.name" . }}
    chart: {{ template "jenkins.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.Service.type }}
  ports:
    - port: {{ .Values.Service.port }}
      targetPort: http
      nodePort: {{ .Values.Service.nodeport }}
      protocol: TCP
      name: http
  selector:
    app: {{ template "jenkins.name" . }}
    release: {{ .Release.Name }}
